"""Type stubs for Brython's browser module.

Provides MyPy-compatible type declarations for the top-level
``browser`` package used in MatHud's client-side Brython code.
Covers ``document``, ``window``, ``html``, ``svg``, ``console``,
and re-exports the ``ajax`` and ``aio`` submodules.
"""

from __future__ import annotations

from typing import Any, Callable

from browser._dom import ClassList as ClassList
from browser._dom import DOMNode as DOMNode
from browser import ajax as ajax
from browser import aio as aio

# ---------------------------------------------------------------------------
# Helper classes for typed Window sub-objects
# ---------------------------------------------------------------------------

class _JSON:
    def stringify(self, obj: Any) -> str: ...
    def parse(self, s: str) -> Any: ...

class _LocalStorage:
    def getItem(self, key: str) -> str | None: ...
    def setItem(self, key: str, value: str) -> None: ...
    def removeItem(self, key: str) -> None: ...

class _Performance:
    def now(self) -> float: ...

class _MathJS:
    def evaluate(self, expr: str, scope: Any = ...) -> Any: ...
    def format(self, val: Any) -> str: ...
    def sqrt(self, x: Any) -> Any: ...
    def pow(self, x: Any, exp: Any) -> Any: ...
    def det(self, matrix: Any) -> Any: ...
    def typeOf(self, val: Any) -> str: ...
    def number(self, val: Any) -> Any: ...
    def matrix(self, data: Any) -> Any: ...

class _NerdamerExpr:
    def text(self) -> str: ...
    def evaluate(self) -> _NerdamerExpr: ...
    def sub(self, var: str, val: Any) -> _NerdamerExpr: ...
    def coeffs(self, var: str) -> _NerdamerExpr: ...

class _Nerdamer:
    def __call__(self, expr: str) -> _NerdamerExpr: ...
    def solveEquations(self, eqs: Any) -> Any: ...
    def coeffs(self, expr: Any, var: str) -> Any: ...

class _Date:
    def now(self) -> int: ...
    def new(self) -> Any: ...

class _URL:
    def createObjectURL(self, blob: Any) -> str: ...
    def revokeObjectURL(self, url: str) -> None: ...

# ---------------------------------------------------------------------------
# Document
# ---------------------------------------------------------------------------

class Document:
    """The browser ``document`` object.

    Not a subclass of ``DOMNode`` to avoid Liskov substitution
    conflicts with differing method signatures.
    """

    def getElementById(self, id: str) -> DOMNode | None: ...
    def querySelector(self, selector: str) -> DOMNode | None: ...
    def select(self, selector: str) -> list[DOMNode]: ...
    def select_one(self, selector: str) -> DOMNode | None: ...
    def createDocumentFragment(self) -> DOMNode: ...
    def execCommand(self, command: str) -> bool: ...
    def bind(self, event: str, handler: Callable[..., Any]) -> None: ...
    def __getitem__(self, key: str) -> DOMNode: ...
    def __contains__(self, key: str) -> bool: ...
    def __le__(self, other: Any) -> None: ...

# ---------------------------------------------------------------------------
# Window
# ---------------------------------------------------------------------------

class Window:
    """The browser ``window`` object.

    Typed sub-objects provide precision for commonly used APIs.
    The ``__getattr__`` / ``__setattr__`` escape hatches cover
    the many dynamic properties (MatHud custom globals, test
    monkey-patching, etc.).
    """

    # Typed sub-objects
    JSON: _JSON
    localStorage: _LocalStorage
    performance: _Performance
    math: _MathJS
    nerdamer: _Nerdamer
    Date: _Date
    URL: _URL

    # Direct methods
    def setTimeout(self, callback: Callable[..., Any], delay: int | float) -> int: ...
    def clearTimeout(self, timer_id: int) -> None: ...
    def requestAnimationFrame(self, callback: Callable[..., Any]) -> int: ...

    # Constructor-like attributes
    Audio: Any
    Float32Array: Any
    FileReader: Any
    MouseEvent: Any
    MathJax: Any
    Math: Any
    document: Any

    # Escape hatches for dynamic properties
    def __getattr__(self, name: str) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

# ---------------------------------------------------------------------------
# HTMLFactory
# ---------------------------------------------------------------------------

class HTMLFactory:
    """Factory for creating HTML elements via ``html.DIV(...)``, etc."""

    def BUTTON(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def CANVAS(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def DETAILS(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def DIV(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def H3(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def IMG(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def INPUT(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def LABEL(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def OPTION(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def P(self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any) -> DOMNode: ...
    def SELECT(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def SPAN(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def SUMMARY(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def TEXTAREA(
        self, content: Any = ..., *, Class: str = ..., id: str = ..., style: Any = ..., **kwargs: Any
    ) -> DOMNode: ...
    def __getattr__(self, name: str) -> Callable[..., DOMNode]: ...

# ---------------------------------------------------------------------------
# SVGFactory
# ---------------------------------------------------------------------------

class SVGFactory:
    """Factory for creating SVG elements via ``svg.line(...)``, etc."""

    def svg(self, **kwargs: Any) -> DOMNode: ...
    def g(self, **kwargs: Any) -> DOMNode: ...
    def line(self, **kwargs: Any) -> DOMNode: ...
    def path(self, **kwargs: Any) -> DOMNode: ...
    def circle(self, **kwargs: Any) -> DOMNode: ...
    def ellipse(self, **kwargs: Any) -> DOMNode: ...
    def polygon(self, **kwargs: Any) -> DOMNode: ...
    def text(self, **kwargs: Any) -> DOMNode: ...
    def __getattr__(self, name: str) -> Callable[..., DOMNode]: ...

# ---------------------------------------------------------------------------
# Console
# ---------------------------------------------------------------------------

class Console:
    """The browser ``console`` object."""

    def log(self, *args: Any) -> None: ...
    def error(self, *args: Any) -> None: ...
    def warn(self, *args: Any) -> None: ...
    def groupCollapsed(self, label: str) -> None: ...
    def groupEnd(self) -> None: ...

# ---------------------------------------------------------------------------
# Module-level instances
# ---------------------------------------------------------------------------

document: Document
window: Window
html: HTMLFactory
svg: SVGFactory
console: Console
