"""Type stubs for Brython browser module."""

from typing import Any, Callable, Optional

class DOMNode:
    """Base DOM node type."""
    def getBoundingClientRect(self) -> Any: ...
    def appendChild(self, child: Any) -> Any: ...
    def removeChild(self, child: Any) -> Any: ...
    def setAttribute(self, name: str, value: str) -> None: ...
    def getAttribute(self, name: str) -> Optional[str]: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

class Document:
    """Document object."""
    def __getitem__(self, key: str) -> DOMNode: ...

document: Document

class HTML:
    """HTML element factory."""
    def __call__(self, tag: str, **kwargs: Any) -> DOMNode: ...

html: HTML

class Ajax:
    """AJAX request handler."""
    def __init__(self, url: str, **kwargs: Any) -> None: ...
    def send(self, *args: Any) -> None: ...
    def bind(self, event: str, handler: Callable[..., None]) -> None: ...

ajax: Any  # Module-level alias

class Window:
    """Browser window object."""
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...

window: Window

class Console:
    """Console object."""
    def log(self, *args: Any) -> None: ...
    def error(self, *args: Any) -> None: ...
    def warn(self, *args: Any) -> None: ...

console: Console

class SVG:
    """SVG element factory."""
    def __call__(self, tag: str, **kwargs: Any) -> DOMNode: ...

svg: SVG
