"""Type stubs for Brython browser DOM types.

Provides MyPy-compatible declarations for DOMNode and ClassList,
the shared base types used across all browser module stubs.
"""

from __future__ import annotations

from typing import Any, Callable

class ClassList:
    """Proxy for the DOM element's classList property."""

    def add(self, token: str) -> None: ...
    def remove(self, token: str) -> None: ...
    def contains(self, token: str) -> bool: ...

class DOMNode:
    """Base DOM node type used throughout Brython's browser module.

    Represents an HTML or SVG element in the browser DOM.  Brython
    maps Python attribute access and operators onto the underlying
    JavaScript DOM API.
    """

    # --- Properties ---
    innerHTML: str
    text: str
    value: Any
    disabled: bool
    checked: bool
    options: Any
    scrollTop: float
    scrollHeight: float
    style: Any
    classList: ClassList
    attrs: dict[str, str]
    parentNode: DOMNode | None
    children: Any
    firstChild: DOMNode | None
    width: Any
    height: Any
    onload: Callable[..., Any] | None
    result: Any
    responseType: str

    # --- Methods ---
    def getBoundingClientRect(self) -> Any: ...
    def appendChild(self, child: DOMNode) -> DOMNode: ...
    def removeChild(self, child: DOMNode) -> DOMNode: ...
    def setAttribute(self, name: str, value: str) -> None: ...
    def getAttribute(self, name: str) -> str | None: ...
    def removeAttribute(self, name: str) -> None: ...
    def insertBefore(self, new_child: DOMNode, ref_child: DOMNode | None) -> DOMNode: ...
    def cloneNode(self, deep: bool = ...) -> DOMNode: ...
    def bind(self, event: str, handler: Callable[..., Any]) -> None: ...
    def focus(self) -> None: ...
    def blur(self) -> None: ...
    def click(self) -> None: ...
    def clear(self) -> None: ...
    def remove(self) -> None: ...
    def getContext(self, context_type: str) -> Any: ...
    def select(self, selector: str) -> list[DOMNode]: ...
    def select_one(self, selector: str) -> DOMNode | None: ...

    # --- Operators ---
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __le__(self, other: Any) -> None: ...  # Brython DOM append via <=
    def __contains__(self, key: Any) -> bool: ...
